# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    TIMER_minute: '%env(APP_TIMER_INACTIF)%'
    app.wsdv_url: '%env(APP_WSDV_URL)%'
    app.wsdv_login : '%env(APP_WSDV_LOGIN)%'
    app.wsdv_password : '%env(APP_WSDV_PASSWORD)%'
    app.hash_key: '%env(APP_HASH_KEY)%'
    app.signrequest_url: '%env(APP_SIGNREQUEST_URL)%'
    app.signrequest_token: '%env(APP_SIGNREQUEST_TOKEN)%'
    app.stripe_token: '%env(APP_STRIPE_TOKEN)%'
    app.email: '%env(APP_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Security\CustomVerySecureHasher:
       arguments:
        $hashKey: '%app.hash_key%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
